global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'navplat-monitor'

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'journey-api'
    static_configs:
      - targets: ['journey-api:80']
    metrics_path: '/metrics'

  - job_name: 'notification-api'
    static_configs:
      - targets: ['notification-api:80']
    metrics_path: '/metrics'

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:80']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

